### ISSUE TITLE
Task retry does not take extra command-line args into account?

### ISSUE THREAD

**Issue by demobox** [HubSpot/Singularity#1133]
We've just seen the following pattern for a request:

1. Task with extra command line args fails
1. New task is created with message `Task launched because of RETRY`
1. New task does not have any extra command line args

Is that expected or a bug?

/cc @ssalinas

**Comment by ssalinas** [comment]
Hey @demobox , apologies for the slow response. To make sure I get the situation correct, I'm assuming this is a `Scheduled` request that you launched with extra command line args using the 'Run Now' option?

If so, that's an interesting one, and brings up the question of whether launching the 'Run Now' with new args should change it for all runs of the scheduled request going forward (essentially creating a new deploy for it). I would argue that in order to change all future tasks' args, you should be posting a new deploy, since 'Run Now' is more of a one-off action.

**Comment by ssalinas** [comment]
To clarify that a bit more succinctly, yes that is what I would expect to happen currently. To change all tasks going forward for the scheduled request, I would recommend a new deploy instead.

**Comment by demobox** [comment]
> To change all tasks going forward for the scheduled request, I would recommend a new deploy instead.

Agreed. That is not the intention here, though - sorry if the description wasn't clear. This is only about how **retries of a failed task** are performed. I.e. if I kick of task A with some extra args, and A fails and I have retries configured for that Request, should the retries of A use the same args?

Obviously, subsequent triggered runs for a scheduled tasks, or direct invocations using "Run now", should probably not inherit these args.

And actually, it wasn't for a scheduled request, but an on-demand one ;-)

Thanks for taking a look, @ssalinas!

**Comment by ssalinas** [comment]
Ah, I had misinterpreted, thanks for clarifying. That is likely a bug then, I would expect that those arguments get carried through for a retry. I can look into a fix for that

**Comment by demobox** [comment]
> I can look into a fix for that

Great, thanks!
