### ISSUE TITLE
Support for mesos attributes

### ISSUE THREAD

**Issue by kchaliki** [HubSpot/Singularity#1159]
Hello - quick question, is there support for requesting that resources offered carry certain mesos attributes?

**Comment by ssalinas** [comment]
Hey @kchaliki , there are two fields on the `SingularityRequest` object, and one on the `SingularityConfiguration` used to start `SingularityService` that implement what you are likely looking for.

#### Only run on a slave that has certain attributes
`requiredSlaveAttributes` (Map<String, String>) - For all tasks for this request, only run them on slaves that contain all attributes specified in this field. For example `"requiredSlaveAttributes":{"name":"bob"}` will only allow the tasks for that request to run on slaves with an attribute `name` that has value `bob`.

#### Reserve slaves with certain attributes for specific requests
- If you set the `reserveSlavesWithAttributes` (Map<String, List<String>) in your SingularityConfiguration, Singularity will not run tasks on that slave unless the corresponding request for those tasks has matching values in `requiredSlaveAttributes` or ...
- `allowedSlaveAttributes` (Map<String, String>) allows tasks for this request to run on slaves with these attributes that would otherwise be reserved (by setting `reserveSlavesWithAttributes`) but does not restrict them solely to those slaves

If neither of these options fit your use case feel free to reopen the issue with a feature request

**Comment by kchaliki** [comment]
@ssalinas thanks for your response - does that mean the feature is not available through the GUI, just the API?

**Comment by ssalinas** [comment]
That used to be the case, but with the most recent release 0.10.0 you can do it in the UI too 😄

**Comment by kchaliki** [comment]
Awesome - thx! Any docs on how to upgrade?

**Comment by ssalinas** [comment]
You can see all of the current Singularity docs at http://getsingularity.com/

**Comment by kchaliki** [comment]
Looks like I don't need to do manage if I am not using the SQL feature - will give it a shot - thanks again
