### ISSUE TITLE
Logrotate custom schedule

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1431]
Hi,  
I dont like mixing singularity logrotate configs with my system logrotate configs, because some directives are outside of file scope, and that affects other config files in the folder. So I set that singularity executor creates logrotate configs in separate directory.  
But how and when executor runs logrotate? How to control it? Is there a way to set it globally or per deploy?

**Comment by ssalinas** [comment]
A few configurable parameters here:

On the [`SingularityExecutorConfiguration`](https://github.com/HubSpot/Singularity/blob/master/SingularityExecutor/src/main/java/com/hubspot/singularity/executor/config/SingularityExecutorConfiguration.java) (i.e. defaults shared for al executors on a host) there is a property called `logrotateConfDirectory`, which is the directory that the logrotate files will be written to. There are a few others in there as well to control the default directory to rotate things to, number to keep, etc.

On the SingularityDeploy there is a field in [`executorData.logrotateFrequency`](https://github.com/HubSpot/Singularity/blob/master/SingularityBase/src/main/java/com/hubspot/deploy/ExecutorData.java#L34) which controls the timing. `MONTHLY`, `WEEKLY`, and `HOURLY` settings all just trigger a logrotate conf file to be written, and logrotate takes care of the rest (except for a manual logrotate when the task is shutting down). An `HOURLY` setting will additionally write a cron file to run logrotate since not all logrotate versions support hourly rotation

**Comment by petrovicboban** [comment]
Thanks for answer.  
It would be nice if we can choose logrotateFrequeny in UI deploy page.

**Comment by ssalinas** [comment]
Will reopen this so we remember to add that field in the deploy form 👍

**Comment by petrovicboban** [comment]
Hi,  
this seems to be forgotten?

**Comment by tpetr** [comment]
@kwm4385 will be shepherding the PR above to master sometime this week.
