### ISSUE TITLE
Allow the log level for the `com.hubspot.singularity` logger to be overridden from the container start script?

### ISSUE THREAD

**Issue by demobox** [HubSpot/Singularity#1512]
The default service configuration sets the log level of the `com.hubspot.singularity` logger [to `TRACE`](https://github.com/HubSpot/Singularity/blob/master/SingularityService/singularity.yml#L32), which is quite verbose and can produce very large log files if the service is running for a long time.

While the [container start script](https://github.com/HubSpot/Singularity/blob/master/SingularityService/src/main/docker/start.sh) allows many of the configuration parameters to be overridden, the log level for this logger is not one of the values that can be changed.

Assuming that it's even possible to override a DropWizard key/value pair setting via system properties (especially one whose key contains `.` characters - the DropWizard docs don't seem clear on that), would it be possible to make this configuration property overridable too?

Happy to put together a PR if this sounds like a useful idea.

**Comment by ssalinas** [comment]
Yeah, I think we need a better setup in general for the docker conatiner, such that we can configure anything in the yaml file, and not have to keep updating it when we add new configuration fields. Internally, we only use it for development, so it hasn't gotten as much attention for extensive configurability.

I could see hooking up something like http://dropwizard.readthedocs.io/en/latest/manual/core.html#man-core-environment-variables so that we can override any property via environment variables instead.

and PRs always welcome ;)

**Comment by PtrTeixeira** [comment]
An alternative is just to mount a new config file to `/etc/singularity/singularity.yaml` when you run the container. That'll just overwrite the default config file

**Comment by demobox** [comment]
> when you run the container. That'll just overwrite the default config file

That's the option we've considered as a short-term fix for this, but in general we'd also like to contribute to making this easier "out of the box", if possible.

Thanks for the suggestion!
