### ISSUE TITLE
Is this project dying?

### ISSUE THREAD

**Issue by petrovicboban** [HubSpot/Singularity#1617]
There is almost none activity in the last two months. Is it some sort of summer break?

**Comment by tpetr** [comment]
Hey @petrovicboban! One of the main Singularity developers has been on paternity leave since the beginning of August, but this project is definitely not dying.

- We released [0.16.2](https://github.com/HubSpot/Singularity/releases/tag/Singularity-0.16.2) on Aug 4th.
- 22 PRs have been merged to master since the last release:
  ```
  tpetr$ git log Singularity-0.16.2...master | grep 'Merge pull' | grep -v 'hs-jenkins-bot/release'
    Merge pull request #1590 from HubSpot/packagejson-tlc
    Merge pull request #1608 from Nitro/fborrego/update-adopters
    Merge pull request #1610 from HubSpot/highlight-new-files
    Merge pull request #1611 from HubSpot/refactor-request-filters
    Merge pull request #1614 from HubSpot/fix-cron-length-validation
    Merge pull request #1603 from HubSpot/reorganize-group-page
    Merge pull request #1606 from HubSpot/0_16_2_docs
    Merge pull request #1605 from whitedr/deploy_id_with_dot
    Merge pull request #1595 from HubSpot/guard-leader-cache-writes
    Merge pull request #1594 from HubSpot/leader-cache-everywhere
    Merge pull request #1592 from HubSpot/resource-usage-ui
    Merge pull request #1598 from HubSpot/timestamp_seconds_fix
    Merge pull request #1597 from HubSpot/shaded_retryer
    Merge pull request #1593 from HubSpot/more_flaky_tests
    Merge pull request #1591 from HubSpot/flaky_test
    Merge pull request #1583 from HubSpot/average-scheduling-delay
    Merge pull request #1588 from HubSpot/guava-cache-expiration-fix
    Merge pull request #1578 from HubSpot/service_to_worker
    Merge pull request #1587 from HubSpot/fix-key-error
    Merge pull request #1586 from HubSpot/tailer-selectall
    Merge pull request #1576 from HubSpot/evenly-spread-task-placement
    Merge pull request #1570 from HubSpot/use-it-or-lose-it
  ```
- We are due for a new release. @baconmania will be doing that sometime this week.

We are happy to fix bugs and add new features suggested the community, but our resources are extremely limited. Our priorities are:
1. Reliability: [People](https://github.com/HubSpot/Singularity/blob/master/Docs/about/adopters.md) depend on Singularity to run their workloads. If there's something wrong with Singularity that prevents it from working properly, we fix it.
2. HubSpot (our employer): Our (the Singuarity developers) jobs are to keep HubSpot's infrastructure running smoothly, so some features end up being prioritized over others. This means that we're not always the quickest to fix cosmetic issues or implement things way outside the scope of our needs.
3. Everything else.

As always, opening PRs or helping review existing PRs are always welcome. Thanks!

(cc: @ssalinas @baconmania @darcatron @kwm4385)

**Comment by petrovicboban** [comment]
Thanks for response!

**Comment by baconmania** [comment]
Hey @petrovicboban, you can now check out our newest release, [Singularity 0.17.0](https://github.com/HubSpot/Singularity/releases/tag/Singularity-0.17.0). Feel free to reopen this issue if you have any further concerns.
