### ISSUE TITLE
REASON_INVALID_OFFERS optional retry

### ISSUE THREAD

**Issue by cabecada** [HubSpot/Singularity#1622]
Hi Team,

singularity Version: 0.14.1
mesos version: 1.2.0

We seem to have a lot of cases of "Task launched with invalid offers: Offer 1b7d8a83-8b6b-47cd-b6a6-fddf4f92eed2-O250453 is no longer valid"

Is it possible to optionally configure a task retry incase of a task  lost due to "REASON_INVALID_OFFERS"
We are in a process to investigate why these happen, but task lost due to those reasons are almost successful in a retry.

**Comment by ssalinas** [comment]
REASON_INVALID_OFFERS generally appears because Singularity and/or the mesos master are too slow to process the tasks being launched. We noticed in versions <15 that our zk usage was slowing down status update processing enough that, with a high count of tasks, the pipe to and from the mesos master was essentially getting clogged. So, Singularity would receive the offer, but that would be delayed behind a bunch of status updates (the mesos java library restricts the processing of events from the mesos master to a single thread). By the time that offer was accepted by singularity and made it back to the mesos master, the master had already expired the offer (expiration time is configurable).

As a short term fix, you could increase the offer expiration timeout on the mesos master. Longer term, we have more permanent fixes for this in 0.15.0 which dramatically speed up status update and offer processing by moving more of the data needed into memory instead of relying on hitting zk each time.

I'm going to close this since the underlying issue has a fix in newer release, feel free to reopen if you are still running into the issue.

**Comment by cabecada** [comment]
Thanks @ssalinas.
There were suggestions to upgrade to a newer version of singularity/mesos but I did not see any previous ticket or new test case addressing this problem.
Anyways thanks for explaining the issue.
Appreciate your help.
