### ISSUE TITLE
Delete deploy API

### ISSUE THREAD

**Issue by lenfree** [HubSpot/Singularity#1793]
I couldn't manage to find docs to delete deploy without deleting request. Is there a way to do this without deleting its request? How about updating an existing deploy directly such as updating containerInfo parameter/s?

**Comment by ssalinas** [comment]
A deploy in Singularity is meant to be immutable. That is by design. If you wish to update the parameters used to run your tasks, you would initiate a new deploy for the same requests. In terms of deleting, Singularity keeps a history of deploys, and if using sql to offload will eventually delete old ones. Previous deploys have no impact on the functionality of the current active deploy, they are just informational.

I'm curious, why do you need to delete these deploys instead of just starting a new one with new parameters?

**Comment by lenfree** [comment]
I see!  I wasn't aware that deploy is designed to be immutable. Sorry, I skipped many parts of doco.  😛 Anyway, in my case, I have just to create another deploy with unique id with new parameters then. Thanks!
