### ISSUE TITLE
SingularityDeployMarker

### ISSUE THREAD

**Issue by JC1738** [HubSpot/Singularity#1807]
I am looking to try and update the User (which currently says N/A) for deploys done by API. 

![image](https://user-images.githubusercontent.com/3421783/41008470-05777e22-68e0-11e8-847d-f3b01775b6be.png)

It looks like that is set via the DeployMarker.User field, however, I don't see how to set a deploy marker via the SingularityDeployRequest.  The DeployRequest does take SingularityDeploy and Message, which I can set the Message, which ends up in the DeployMarker, but according to the documentation, there is no User on SingularityDeployRequest?

![image](https://user-images.githubusercontent.com/3421783/41008552-792ddd5c-68e0-11e8-94f1-7bed76025d81.png)

**Comment by JC1738** [comment]
@segfaultax

**Comment by ssalinas** [comment]
A few things:
- `SingularityDeployMarker` is never consumed by the API, it's just a holder for bits of information about the deploy
- Since Singularity doesn't have auth built-in it uses a simple default way of parsing the user, which is just a `?user=username` query param on the calls (you should see the UI adding this if you check the calls it makes). We did add [webhook auth](http://getsingularity.com/Docs/features/auth.html) (similar to what kubernetes has available), but without that configured it will default to just using the query param
