### ISSUE TITLE
how does SingularityS3Downloader "avoid use page cache" works

### ISSUE THREAD

**Issue by WhiteDevilBan** [HubSpot/Singularity#1872]
Hi, 
  I seen your doc "how it works", and learn that the SingularityS3Downloader can avoid use page cache, and I look at the code, you are using cmd call wget download file. Then I used it too, but I still got page cache oom error, so can you tell more
  Thanks!

**Comment by ssalinas** [comment]
The downloader 'avoiding the page cache' is more simply put that it is using memory outside of the container trying to be launched. In other words, your task won't oom from a mishandled download, since the memory being used is in a shared pool on the host, not the memory of the executor process which is inside the container (and therefor limited by cgroups/etc). It also allows you to inject S3 access/secret keys more easily, allowing the downloader to hold master keys as opposed to generating expiring urls for downloads
