### ISSUE TITLE
Is there a way to run Singularity tasks as non root and still have access to sandbox

### ISSUE THREAD

**Issue by mikebell90** [HubSpot/Singularity#2040]
I'm wondering if there's a knob somewhere to make the sandbox accessible to the uid or globally (obviously the last is worse)

**Comment by mikebell90** [comment]
Basically the question is how to set a mode/user for the sandbox?

**Comment by ssalinas** [comment]
[MESOS-8332](https://issues.apache.org/jira/browse/MESOS-8332) was the update that changed the sandbox permissions. As far as I know there is not a mesos input or flag to change the sandbox permissions per task. We do a little munging in the SingularityExecutor depending on how the users are setup (with our executor can either run the whole thing as a user, or run as root and have executor switch user, we munge sandbox permissions for the second of those), because we ran into a similar problem after that upgrade.

What version are you on and are you using the default mesos executor or the Singularity one?

**Comment by mikebell90** [comment]
I believe we are on singularity .23 though it might be .22. We use the default mesos executor . I’m gleaning you are saying yes there might be a way but only on singularity executor

**Comment by ssalinas** [comment]
hmm, the default mesos slave + executor should already be setting the permissions correctly for a non-root user to utilize the sandbox. What mesos version as well?

**Comment by mikebell90** [comment]
I’ll try to check tomorrow thanks

**Comment by mikebell90** [comment]
Wasn't able to get this working, but we no longer need this so clearing your board.
