### ISSUE TITLE
HTTP params are included in the file names of downloaded files

### ISSUE THREAD

**Issue by rwalsh849** [HubSpot/Singularity#562]
Consider the following hypothetical deploy (copied from examples.md). The URIs have parameters appended, which is a requirement of my online file storage service, in order to have secure URIs.

I've found that Singularity saves these files with file names that include the parameters. For example, the jar file name is "helloworld-1.0-SNAPSHOT.jar?accessKey=123" after download. In stderr, I see "Error: Unable to access jarfile helloworld-1.0-SNAPSHOT.jar"

The version on my server is 0.4.2-SNAPSHOT.

Thanks in advance for your help. Let me know if you require any further details to reproduce.
```
{
    "deploy": {
        "requestId": "mesos-dropwizard-service",
        "id": "1",
        "command": "java -jar helloworld-1.0-SNAPSHOT.jar server example.yml",
        "resources": {
            "cpus": 0.1,
            "memoryMb": 128,
            "numPorts": 0
        },
        "uris": [
            "https://myCDNExample.com/releases/download/1.0/helloworld-1.0-SNAPSHOT.jar?accessKey=123", 
            "https://myCDNExample.com/releases/download/1.0/example.yml?accessKey=123"
        ],
        "skipHealthchecksOnDeploy": false
    }
}
```

**Comment by tpetr** [comment]
Hey @rwalsh849 -- this is actually a "feature" of the default Mesos executor (which just blindly downloads whatever URI(s) you provide). Here's a couple of workarounds you could try:

- Try using a glob in your command (i.e. `helloworld-1.0-SNAPSHOT.jar*`)
- Try bundling your files in a tarball -- the executor should automatically untar them for you, thus preserving the original filenames
- Try using our custom `SingularityExecutor` instead -- it provides many benefits over the default executor, including:
  - embedded artifacts (i.e. directly embed the contents of your config YAML in the Deploy object)
  - downloads from S3 without having to generate a temporary URL

I'm personally biased towards using the SingularityExecutor, but it takes a little extra setup on your slaves in order to work. Check out https://github.com/HubSpot/Singularity/blob/master/Docs/slave_extras.md for more info, or feel free to ping me if you have specific questions.

**Comment by rwalsh849** [comment]
Thanks @tpetr, these are all great suggestions for working around this. I just tested the glob approach and it works for me.

Thanks also for pointing me at the extras document, I'll consider this as a more sustainable solution.
