### ISSUE TITLE
Singularity executor expects app folder to exist in task sandbox

### ISSUE THREAD

**Issue by tpetr** [HubSpot/Singularity#768]
This could be an oversight on our end -- HubSpot's build artifacts always contain an `app` folder by default.

**Comment by ssalinas** [comment]
The name of that folder is currently configurable in the executor configuration (`taskAppDirectory`) looks like we have a mkdir -p  in the wrapper script for logDir and ./tmp but now `taskAppDirectory`

**Comment by ssalinas** [comment]
Figured out the issue for this btw, when downloading artifacts the executor tries to do a copy to a path that includes the taskAppDirectory. So, doesn't matter that we have a mkdir in our runner script, because it tries to use it before that. The executor should probably create the directory it is trying to place the artifact in if it doesn't exist yet.

**Comment by ssalinas** [comment]
After testing a bit more, seems it wasn't the artifact downloader after all, previous statement was correct that we just need a mkdir -p in there for {{{ taskAppDirectory }}} as well. Fixed in #960
