### ISSUE TITLE
Parallel tasks within a SERVICE or WORKER

### ISSUE THREAD

**Issue by subratbasnet** [HubSpot/Singularity#946]
I create a new request of type "SERVICE" or "WORKER".

When I deploy 3 tasks within that request, each with a unique deploy id - each new task kills the previous task before spawning itself. Is this expected behaviour?

I was looking for a "parallel task within same request" behaviour, which did not kill other running tasks.

I understand there is a feature called "instances", but I do not want to spawn all tasks right away; and each task have slightly different docker environment variable parameters.

How can I go about it?

Thanks!

**Comment by subratbasnet** [comment]
Could this be because I have disabled health checks, and Singularity killed it because it thought the other tasks were unhealthy?

**Comment by ssalinas** [comment]
That is expected behavior in Singularity. A deploy is a new configuration for all tasks running under that request. So, you have an 'active deploy' that is the current configuration for all running tasks under that request. When you create a new deploy, new tasks (corresponding to number of instances) are created with the new configuration. When those new deploy tasks are healthy, the new deploy becomes the 'active deploy' and tasks from the old deploy are shut down. More docs on this [here](https://github.com/HubSpot/Singularity/blob/master/Docs/reference/requests_and_deploys.md).

If you need different tasks with different configuration running in different timings, I would suggest creating separate requests for them. Then, they are completely independent and a deploy of one will not impact the others.

**Comment by subratbasnet** [comment]
Great thanks, closing this.
