### ISSUE TITLE
Task bounce expires but no new task scheduled

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/Singularity#972]
Today we experienced a task which was commanded to bounce, but the new task was unable to launch for some reason.  This led to a state where the existing task is in the `CLEANING` state waiting for a new task to come up, but there was no scheduled task ever to be seen.  Seen on 0.4.11

[Singularity logs for the task](https://gist.github.com/stevenschlansker/ef9ef4f29ce54e0e51d6)

![screenshot_2016-03-24_16-18-56](https://cloud.githubusercontent.com/assets/129097/14033999/30df8d16-f1dc-11e5-996f-7db67c6dfb5f.png)
![screenshot_2016-03-24_16-19-17](https://cloud.githubusercontent.com/assets/129097/14033998/30ded308-f1dc-11e5-8f15-b1b1d70e5d6b.png)

**Comment by ssalinas** [comment]
We've found the issue for this, but the solution might be a bit tricky. Main issue is that we weren't updating the task history. We remove the cleanup, but because the last history is a cleaning state, the task remains in cleaning.

Unfortunately the solution is not as simple as adding another history entry, because the states are stored in zk under the extended task state (i.e. TASK_RUNNING is part of the zk path) and are assumed to come in a logical progression. So we can't just add another TASK_RUNNING on the end. We are investigating options still, just wanted to keep this updated.

**Comment by stevenschlansker** [comment]
Thanks for looking into this, this is the first time we've seen this so I can't claim it's super urgent for us.  But I bet it happens elsewhere and nobody notices, so it'd be worth fixing anyway :)

Excited to see what the solution ends up being.

**Comment by ssalinas** [comment]
Meant to clarify this more the other day. The 'no new task scheduled' part of this actually correct, just the display of the task as still being in cleaning is wrong. We have deleted the request for singularity to clean/replace the task, but because of the task history update for the `TASK_CLEANING` state still being present, the task still shows as being in cleaning when it should actually be running. Currently, looks like our solution is going to be to remove that `TASK_CLEANING` history update (as long as there is no other reason for it to be cleaning) to return it to it's previous status.

This will be fixed by #975
